### ISSUE TITLE
Issue with else conditionals that check for a property

### ISSUE THREAD

**Issue by lzilioli** [zordius/lightncandy#254]
It seems as though lightncandy 1.0 can not properly compile slightly more complex if/else expressions:

```
    // error.php in the gist
    <div class="foo">
        {{#if failed}}
            failed
        {{else if complete}}
            complete
        {{else }}
            fallback
        {{/if}}
        <div class="bar
        {{#if failed}}
        failed
        {{else if complete}}
        complete
        {{/if}}">
    </div>
```

The above used to work in 0.93, but now throws an error in 1.0.0 during template compilation. 

The error:

```
Fatal error: Uncaught exception 'Exception' with message '{{else}} only valid in if, unless, each, and #section context' in error.php on line 45

Exception: {{else}} only valid in if, unless, each, and #section context in vendor/zordius/lightncandy/src/LightnCandy.php on line 108
```

Constructing the statement as follows resolves the compilation error:

```
    // fix.php in the gist
    <div class="foo">
        {{#if failed}}
            failed
        {{else}}{{#if complete}}
            complete
        {{else}}
            fallback
        {{/if}}{{/if}}
        <div class="bar
        {{#if failed}}
        failed
        {{else}}{{#if complete}}
        complete
        {{/if}}{{/if}}">
    </div>
```

Here is a complete gist that I believe **should** illustrate the issue: https://gist.github.com/lzilioli/18c74a0e01a74290a603e8c2256ff4cd

main.php illustrates a working template while error.php illustrates a template that throws the error described in README.md. In v0.93, this error was not thrown, while in 1.0.0 it is.

I was not able to verify that the error is thrown by my reduced test case, as I do not have a new enough version of php installed locally, however this represents the set of changes applied to fix the template compilation within a larger codebase that I recently upgraded to lightncandy 1.0.

**Comment by zordius** [comment]
Example jsfiddle created: https://jsfiddle.net/9zr1x5q2/

**Comment by zordius** [comment]
Confirmed the code works as expected in v1.0.0 and v1.0.1:

```php
require_once('vendor/autoload.php');
use LightnCandy\LightnCandy;
$template = '
{{#if failed}}
a
{{else if complete}}
b
{{else if current }}
c
{{else }}
d
{{/if}}';
$phpStr = LightnCandy::compile($template, array(
  'flags' => 0
    | LightnCandy::FLAG_BESTPERFORMANCE
    | LightnCandy::FLAG_ERROR_EXCEPTION
    | LightnCandy::FLAG_RUNTIMEPARTIAL
    | LightnCandy::FLAG_SPACECTL
    | LightnCandy::FLAG_SPVARS
    | LightnCandy::FLAG_HANDLEBARS
));
$output = eval($phpStr);
echo $output(array('failed'=>true));
echo $output(array('complete'=>true));
echo $output(array('current'=>true));
echo $output(array());
```

Output:
```

a

b

c

d
```

**Comment by zordius** [comment]
Hello, maybe you can remove the vendor directory then composor install a new environment to test again, thanks. So far I can not reproduce the issue at my side.

**Comment by lzilioli** [comment]
@zordius my apologies, as I mentioned I was not able to test locally yesterday when opening the issue. I am now able to do so, and can reproduce the issue with the updated gist:

https://gist.github.com/lzilioli/18c74a0e01a74290a603e8c2256ff4cd

**Comment by zordius** [comment]
New jsfiddle example created: https://jsfiddle.net/xk1y7b76/

**Comment by zordius** [comment]
confirmed as a bug.

**Comment by zordius** [comment]
It should be fixed in current master, please try again, thanks.

**Comment by lzilioli** [comment]
@zordius fix looks good both in the demo gist as well as in our greater codebase. Would you mind publishing the 1.0.2 release so that we can upgrade? Thanks a bunch!

**Comment by zordius** [comment]
released as 1.0.2
